# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Wasp Robot
email: wasonrohit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a full-stack, agile, software developer by the day, a dancer by the evening, and a dad in between all that
  I have many musings about technology, dance and life. This is the home of my musings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wasprobot.github.io" # the base hostname & protocol for your site
twitter_username: wasprobot
github_username:  wasprobot

# Build settings
markdown: kramdown
