# Site settings
title: "Rohit Wason"
description: "The wasp-robot"
baseurl: ""
url: "http://wasprobot.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 3

# Links
links:
  - title: "resume"
    url: /resume
  - title: "twit"
    url: http://twitter.com/wasprobot
  - title: "git"
    url: http://github.com/wasprobot
  - title: "rss"
    url: /feed.xml

# Plugins
gems:      [jekyll-paginate]
